### PR TITLE
WIP: Schedules exported in iCalendar format

### PR DESCRIPTION
**Pull request by ticky**
This is my attempt at a resolution for #14. I’ve only managed to do an initial pass at this, but I’d love to get your feedback on the approach early!

screen shot 2018-04-04 at 6 21 30 pm
screen shot 2018-04-04 at 6 20 11 pm

### CODE REVIEW

**Comment by ticky** [comment]
So far, this adds a calendar export method to `CoopSchedulesUpdater`, using `cozy-ical` (`ical.js` doesn’t provide much other than a converter to a JSON representation of the otherwise raw iCalendar format, which didn’t feel quite right for use here to me!) to produce a file named the same as the JSON export.

I also realise that this makes _zero_ attempt at internationalisation. It’d be *extra* neat if we could get it so that it produces several localised versions of the calendar export, and I feel like this is possible, but I’ve yet to dig into the localisation infrastructure to figure out if an i18n pass is doable at import time. At first glance it looks like it’s only got a Vue filter interface.

Finally, I will give a look at the option of using a similar `jsonpath`-based method for defining event data structures so that this logic can be moved up into the `Updater` class, but I’m yet to come up with a good way to allow for the several locales required for Splatfests, or for the different descriptions necessary for the different event types.

**Comment by misenhower** [comment]
That is super cool, thanks for your effort here! I will take a look and dig into this as soon as I get some time.

The localization stuff is fairly complex because (other than some core UI strings) it's all dynamic and additional region data is loaded on demand. (There are some additional complications, e.g., not all languages are available in all Splatoon regions so it has to retrieve certain languages using different API keys, etc.)

Anyway, thanks again and I will see if I can adapt this for use with Splatfests 😃

**Comment by misenhower** [comment]
Also, apologies for having to deal with the messy updater code 😬 (There is a lot I want to clean up eventually in this project!)

**Comment by ticky** [comment]
No problem Matt! I’m hoping to take a look at the Splatfests and normal/ranked/competitive battle schedules myself, but this felt like a good spot to pause for some feedback :)

**Pull request merged**
